In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_columns', None)

In [4]:
data = "Data/2022-01-01-2023-01-17-Europe-Ukraine.csv"
ukraine_df = pd.read_csv(data)
ukraine_df.head()

,data_id,iso,event_id_cnty,event_id_no_cnty,event_date,year,time_precision,event_type,sub_event_type,actor1,assoc_actor_1,inter1,interaction,region,country,admin1,admin2,admin3,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,timestamp,iso3
0,9778529,804,UKR87293,87293,13 January 2023,2023,1,Battles,Armed clash,Military Forces of Russia (2000-),Wagner Group,8,18,Europe,Ukraine,Donetsk,Bakhmutskyi,Soledarska,Soledar,48.6969,38.0611,2,Ministry of Defence of Ukraine,Other,"On 13 January 2023, Russian forces, including ...",0,1673986322,UKR
1,9778529,804,UKR87293,87293,13 January 2023,2023,1,Battles,Armed clash,Military Forces of Ukraine (2019-),NaN,1,18,Europe,Ukraine,Donetsk,Bakhmutskyi,Soledarska,Soledar,48.6969,38.0611,2,Ministry of Defence of Ukraine,Other,"On 13 January 2023, Russian forces, including ...",0,1673986322,UKR
2,9778632,804,UKR87396,87396,13 January 2023,2023,1,Battles,Armed clash,Military Forces of Russia (2000-),NaN,8,18,Europe,Ukraine,Donetsk,Bakhmutskyi,Bakhmutska,Bakhmut,48.5956,37.9999,2,Ministry of Defence of Ukraine,Other,"On 13 January 2023, Russian forces shelled, as...",0,1673986322,UKR
3,9778632,804,UKR87396,87396,13 January 2023,2023,1,Battles,Armed clash,Military Forces of Ukraine (2019-),NaN,1,18,Europe,Ukraine,Donetsk,Bakhmutskyi,Bakhmutska,Bakhmut,48.5956,37.9999,2,Ministry of Defence of Ukraine,Other,"On 13 January 2023, Russian forces shelled, as...",0,1673986322,UKR
4,9778633,804,UKR87397,87397,13 January 2023,2023,1,Battles,Armed clash,Military Forces of Russia (2000-),NaN,8,18,Europe,Ukraine,Luhansk,Sievierodonetskyi,Lysychanska,Bilohorivka,48.9259,38.2467,2,Ministry of Defence of Ukraine,Other,"On 13 January 2023, Russian forces shelled, as...",0,1673986322,UKR

In [5]:
clean_df1 = ukraine_df.drop(columns=['iso', 'event_id_cnty', 'event_id_no_cnty', 'time_precision', 'inter1', 'region', 'country', 'geo_precision', 'iso3'])
clean_df1.head()

,data_id,event_date,year,event_type,sub_event_type,actor1,assoc_actor_1,interaction,admin1,admin2,admin3,location,latitude,longitude,source,source_scale,notes,fatalities,timestamp
0,9778529,13 January 2023,2023,Battles,Armed clash,Military Forces of Russia (2000-),Wagner Group,18,Donetsk,Bakhmutskyi,Soledarska,Soledar,48.6969,38.0611,Ministry of Defence of Ukraine,Other,"On 13 January 2023, Russian forces, including ...",0,1673986322
1,9778529,13 January 2023,2023,Battles,Armed clash,Military Forces of Ukraine (2019-),NaN,18,Donetsk,Bakhmutskyi,Soledarska,Soledar,48.6969,38.0611,Ministry of Defence of Ukraine,Other,"On 13 January 2023, Russian forces, including ...",0,1673986322
2,9778632,13 January 2023,2023,Battles,Armed clash,Military Forces of Russia (2000-),NaN,18,Donetsk,Bakhmutskyi,Bakhmutska,Bakhmut,48.5956,37.9999,Ministry of Defence of Ukraine,Other,"On 13 January 2023, Russian forces shelled, as...",0,1673986322
3,9778632,13 January 2023,2023,Battles,Armed clash,Military Forces of Ukraine (2019-),NaN,18,Donetsk,Bakhmutskyi,Bakhmutska,Bakhmut,48.5956,37.9999,Ministry of Defence of Ukraine,Other,"On 13 January 2023, Russian forces shelled, as...",0,1673986322
4,9778633,13 January 2023,2023,Battles,Armed clash,Military Forces of Russia (2000-),NaN,18,Luhansk,Sievierodonetskyi,Lysychanska,Bilohorivka,48.9259,38.2467,Ministry of Defence of Ukraine,Other,"On 13 January 2023, Russian forces shelled, as...",0,1673986322

In [6]:
clean_df2 = clean_df1.drop(columns=['source_scale'])
clean_df2.head()

,data_id,event_date,year,event_type,sub_event_type,actor1,assoc_actor_1,interaction,admin1,admin2,admin3,location,latitude,longitude,source,notes,fatalities,timestamp
0,9778529,13 January 2023,2023,Battles,Armed clash,Military Forces of Russia (2000-),Wagner Group,18,Donetsk,Bakhmutskyi,Soledarska,Soledar,48.6969,38.0611,Ministry of Defence of Ukraine,"On 13 January 2023, Russian forces, including ...",0,1673986322
1,9778529,13 January 2023,2023,Battles,Armed clash,Military Forces of Ukraine (2019-),NaN,18,Donetsk,Bakhmutskyi,Soledarska,Soledar,48.6969,38.0611,Ministry of Defence of Ukraine,"On 13 January 2023, Russian forces, including ...",0,1673986322
2,9778632,13 January 2023,2023,Battles,Armed clash,Military Forces of Russia (2000-),NaN,18,Donetsk,Bakhmutskyi,Bakhmutska,Bakhmut,48.5956,37.9999,Ministry of Defence of Ukraine,"On 13 January 2023, Russian forces shelled, as...",0,1673986322
3,9778632,13 January 2023,2023,Battles,Armed clash,Military Forces of Ukraine (2019-),NaN,18,Donetsk,Bakhmutskyi,Bakhmutska,Bakhmut,48.5956,37.9999,Ministry of Defence of Ukraine,"On 13 January 2023, Russian forces shelled, as...",0,1673986322
4,9778633,13 January 2023,2023,Battles,Armed clash,Military Forces of Russia (2000-),NaN,18,Luhansk,Sievierodonetskyi,Lysychanska,Bilohorivka,48.9259,38.2467,Ministry of Defence of Ukraine,"On 13 January 2023, Russian forces shelled, as...",0,1673986322

In [7]:
clean_df3 = clean_df2.drop(columns=['assoc_actor_1'])
clean_df3.head()

,data_id,event_date,year,event_type,sub_event_type,actor1,interaction,admin1,admin2,admin3,location,latitude,longitude,source,notes,fatalities,timestamp
0,9778529,13 January 2023,2023,Battles,Armed clash,Military Forces of Russia (2000-),18,Donetsk,Bakhmutskyi,Soledarska,Soledar,48.6969,38.0611,Ministry of Defence of Ukraine,"On 13 January 2023, Russian forces, including ...",0,1673986322
1,9778529,13 January 2023,2023,Battles,Armed clash,Military Forces of Ukraine (2019-),18,Donetsk,Bakhmutskyi,Soledarska,Soledar,48.6969,38.0611,Ministry of Defence of Ukraine,"On 13 January 2023, Russian forces, including ...",0,1673986322
2,9778632,13 January 2023,2023,Battles,Armed clash,Military Forces of Russia (2000-),18,Donetsk,Bakhmutskyi,Bakhmutska,Bakhmut,48.5956,37.9999,Ministry of Defence of Ukraine,"On 13 January 2023, Russian forces shelled, as...",0,1673986322
3,9778632,13 January 2023,2023,Battles,Armed clash,Military Forces of Ukraine (2019-),18,Donetsk,Bakhmutskyi,Bakhmutska,Bakhmut,48.5956,37.9999,Ministry of Defence of Ukraine,"On 13 January 2023, Russian forces shelled, as...",0,1673986322
4,9778633,13 January 2023,2023,Battles,Armed clash,Military Forces of Russia (2000-),18,Luhansk,Sievierodonetskyi,Lysychanska,Bilohorivka,48.9259,38.2467,Ministry of Defence of Ukraine,"On 13 January 2023, Russian forces shelled, as...",0,1673986322

In [8]:
clean_df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54837 entries, 0 to 54836
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   data_id         54837 non-null  int64
 1   event_date      54837 non-null  object
 2   year            54837 non-null  int64
 3   event_type      54837 non-null  object
 4   sub_event_type  54837 non-null  object
 5   actor1          54837 non-null  object
 6   interaction     54837 non-null  int64
 7   admin1          54821 non-null  object
 8   admin2          54739 non-null  object
 9   admin3          54357 non-null  object
 10  location        54837 non-null  object
 11  latitude        54837 non-null  float64
 12  longitude       54837 non-null  float64
 13  source          54837 non-null  object
 14  notes           54837 non-null  object
 15  fatalities      54837 non-null  int64
 16  timestamp       54837 non-null  int64
dtypes: float64(2), int64(5), object(10)
memory usage: 7.1+ MB

In [9]:
# Next steps include further cleaning of the data, creating a random sample of the data for 1000 events, turning that dataframe
# into JSON, and then preparing it for ingestion for the website.